import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          999leaks
        </h1>

        <p>
            All the Juice WRLD leaks in one place
        </p>

        <div className="frcss_cardGrid">
          <a href="https://nextjs.org/docs" className="frcss_card">
            <h3>Documentation</h3>
          </a>

          <a href="https://nextjs.org/learn" className="frcss_card">
            <h3>Learn</h3>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="frcss_card"
          >
            <h3>Examples</h3>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="frcss_card"
          >
            <h3>Deploy</h3>
          </a>
        </div>
      </main>
    </div>
  )
}
